BerkeleyDBC : [HAVE_CRYPTO] [HAVE_HASH] [HAVE_REPLICATION] [HAVE_VERIFY] PAGESIZE CACHESIZE [HAVE_SEQUENCE] [HAVE_STATISTICS] [DIAGNOSTIC] :: _BerkeleyDBC ;
PAGESIZE : PS1K | PS4K | PS8K | PS16K | PS32K :: _PAGESIZE ;
CACHESIZE : CS16MB | CS32MB | CS64MB | CS512MB :: _CACHESIZE ;